export const reducerCases = {
    SET_TOKEN: 'SET_TOKEN',
    SET_USER: 'SET_USER',
    SET_USER_PLAYLISTS: 'SET_USER_PLAYLISTS',
    SET_FEATURED_PLAYLISTS: 'SET_FEATURED_PLAYLISTS',
    SET_FEATURED_ALBUMS: 'SET_FEATURED_ALBUMS',
    SET_PLAYING: 'SET_PLAYING',
    SET_BROWSE_CATEGORIES: 'SET_BROWSE_CATEGORIES',
    SET_ITEM: 'SET_ITEM',
    SET_APPSTATE : 'SET_APPSTATE',
    SET_TOP_TRACKS: 'SET_TOP_TRACKS',
    SET_TOP_ARTISTS: 'SET_TOP_ARTISTS',
    SET_FOLLOWED_ARTIST : 'SET_FOLLOWED_ARTIST'
}